const DistrictAwardOfMeritAlumni = [ // 0 left spaces so it sorts to top with 'sort /r'
	// sort with this: %!sort /r
  ["2024<!--Dawn-eMail-4.7.2025!-->, Hankins, Mary"],
  ["2024<!--Dawn-eMail-4.7.2025!-->, Hankins, Josh"],
  ["2024<!--Dawn-eMail-4.7.2025!-->, Crippen, Matthew, Sr."],
  ["2023, Fewins-Bliss, Larry"],
  ["2022<!--(ChiefOrecords)!-->, Todd, Aaron "],
  ["2022<!--(ChiefOrecords)!-->, Ekola, Marla"],
  ["2021<!--(ChiefOrecords)!-->, Neely, Kevin "],
  ["2021<!--(ChiefOrecords)!-->, Daman, Dusty "],
  ["2021<!--(ChiefOrecords)!-->, Chance, Carrie "],
  ["2020<!--(MCCexport)!-->, Meadows, Dawn"],
  ["2020<!--(MCCexport)!-->, McNeely, Robert"],
  ["2020, Leibrand, Lisa"],
  ["2019<!--(MCCexport)!-->, Rawson, David"],
  ["2019, Rustem, Raymond"],
  ["2019, Leibrand, Charles"],
  ["2019, Foster, Ashley"],
  ["2018<!--(MCCexport)!-->, Triplett, Nathan"],
  ["2018<!--(MCCexport)!-->, Oberg, Steven"],
  ["2018<!--(MCCexport)!-->, Johnson, Derek"],
  ["2017<!--(MCCexport)!-->, Chance, Nathan"],
  ["2017, Ross, Elizabeth"],
  ["2014<!--(MCCexport)!-->, Moore, Sheril"],
  ["2013<!--(MCCexport)!-->, McNeilly, Paul"],
  ["2013<!--(MCCexport)!-->, Louney, Dennis"],
  ["2013<!--(MCCexport)!-->, Lance, John"],
  ["2013<!--(MCCexport)!-->, Cotter, Sean"],
  ["2013, Sauer, Robert"],
  ["2013, Craw, Kirby"],
  ["2011, Musson, Timothy"],
  ["2007, Koepf, Harley"],
  ["2006, Alman, Shirley"],
  ["2005, Stauffer, John"],
  ["2003, Wendorf, Melissa"],
  ["2003, Reinewald, Henry"],
  ["2003, Colf, Bryan"],
  ["2001, Cornell, Robert"],
  ["2000, Savage, Chris"],
  ["2000, Roney, Terry"],
  ["2000, Ritchison, Roderick"],
  ["2000, Pulver, Joseph"],
  ["2000, Proctor, Lawrence"],
  ["2000, Lowe, Steve"],
  ["1999, Murray, Brad"],
  ["1999, Izdebski, Stephen"],
  ["1995, Moore, David"],
  ["1994, Riggins, Ricky"],
  ["1994, Cerny, Russell"],
  ["1981, Smith, Gail"],
  ["1981, Emery, James"],
  // 2 left spaces so these lines sort between top and bottom
   // ["<ul><li>- MCCexport - just in MCC's Export<li>- ChiefOrecords - just in current Chief<br> &nbsp; &nbsp; Okemos spreadsheet</ul>"]
    ] // 4 left spaces so it sorts to bottom with : %!sort /r
