const ChiefOkemosDistrictAwards = [
	// DON'T SORT this! the order is manual...
  ["2024, Charter Organizational Representative of the Year : George Weygandt, Troop 129"],
  ["2024, Charter Organization of the Year : St. Gerard Catholic Church, Troop 164"],
  ["2024, Committee Chairperson of the Year : Erin West, Troop 763"],
  ["2024, Committee Chairperson of the Year, Linked Troops : Lise Mitchell, Crew 2, Troop 2B, Troop 2G"],
  ["2024, Community Leadership Award : Knights of Columbus #788"],
  ["2024, Crew Advisor of the Year : Tim Musson, Crew 2"],
  ["2024, Crew of the Year : Crew 43"],
  ["2024, Cubmaster of the Year : Sara Watros, Pack 267"],
  ["2024, Den Chief of the Year : Alex Johnson, Pack 121"],
  ["2024, Scouting Family of the Year : Budzyn Family, Troop 2"],
  ["2024, Jack of All Trades : Mindy Moore, Pack 141"],
  ["2024, Pack of the Year : Pack 121"],
  ["2024, Popcorn Kernel of the Year : Derek Johnson, Troop 77 & Troop 111"],
  ["2024, Rookie of the Year, Cub Scout Pack : Kevin Sutton, Pack 141"],
  ["2024, Rookie of the Year, Scouts BSA Troop : Eva Metzger, Troop 164"],
  ["2024, Scoutmaster of the Year : Melinda Locher-Jones, Troop 72"],
  ["2024, Scoutmaster of the Year, Linked Troops : Colleen Cunningham & Joe Budzyn, Troop 2, Boys & Girls"],
  ["2024, Troop of the Year : Troop 63B"],
  ["2024, Scout Spirit of the Year : Peyton Dorceus, Troop 77"],
  ["2024, Chief Okemos Special Recognition - Fundraising : Ginger Koester Chief Okemos & MCC"],
  ["<hr>"],
  ["2023, Charter Organization Representative of the year : George (Chip) Weygandt"],
  ["2023, Chartered Partner Award : St. Gerard Catholic Church"],
  ["2023, Committee Chair of the Year : Erin West"],
  ["2023, Committee Chair of the Year, Linked Units : Lise Mitchell"],
  ["2023, Community Leadership Award : Chris Wegener- Knights of Columbus #788 Grand Knight"],
  ["2023, Crew Advisor of the Year : Tim Musson"],
  ["2023, Cubmaster of the Year : Sara Watros"],
  ["2023, Den Chief of the Year : Alex Johnson"],
  ["2023, Family of the Year : Budzyn Family"],
  ["2023, Jack of all Trades Award : Mindy Moore"],
  ["2023, Pack of the Year : Pack 121"],
  ["2023, Popcorn Kernel of the Year : Derek Johnson"],
  ["2023, Rookie of the Year, Cub Scout Pack : Kevin Sutton"],
  ["2023, Rookie of the Year, Scouts BSA Troop : Eva Metzger"],
  ["2023, Scoutmaster of the Year : Melinda Locher-Jones"],
  ["2023, Scoutmasters of the Year, Linked Troops : Colleen Cunningham & Joe Budzyn"],
  ["2023, Troop of the Year : Troop 63B"],
  ["2023, Scout Spirit of the Year, Youth : Peyton Dorceus"],
  ["<hr>"],
  ["2022, Chartered Org of the Year : Jon Lundy"],
  ["2022, Scoutmaster of the Year : Corey Krystyniak, Troop 63"],
  ["2022, Troop of the Year : Troop 293 (E. Lansing)"],
  ["2022, Cubmaster of the Year : Jason Griffin, Pack 262"],
  ["2022, Pack of the Year : Pack 645/647"],
  ["2022, Jack of all Trades : Paul McNeilly"],
  ["2022, Rookie of the Year : Kristin Schulte"],
  ["2022, Family of the Year : Patterson Family"],
  ["2022, Dynamic Duo of the year : Bryan Gehrcke, Troop 129 & John Sheehan, Pack 258"],
  ["<hr>"],
  ["2021, Chartered Org of the Year : Okemos Community Church"],
  ["2021, Community Partner of the Year : MSUFCU"],
  ["2021, Scoutmaster of the Year : Marla Ekola"],
  ["2021, Troop of the Year : Troop 763 (Mason)"],
  ["2021, Cubmaster of the Year : Steve Bartig (Pack 263)"],
  ["2021, Pack of the Year : Pack 265"],
  ["2021, Jack of all Trades : Tim Musson"],
  ["2021, Rookie of the Year : Aaron Southwell"],
  ["2021, Family of the Year : Tim, Betsy Crippen"],
  ["<hr>"],
  ["2020, Chartered Org of the Year : Grand Ledge Lions Club"],
  ["2020, Community Partner of the Year : Delta Floats"],
  ["2020, Scoutmaster of the Year : Matt Jones, Troop 72 (St. Johns)"],
  ["2020, Troop of the Year : Troop 164 (Okemos)"],
  ["2020, Cubmaster of the Year : Larry Fewins-Bliss (Pack 267)"],
  ["2020, Pack of the Year : Pack 258 (Portland)"],
  ["2020, Jack of all Trades : Nate Chance, Troop 901 & 260"],
  ["2020, Rookie of the Year : Ed Lutz, Pack 260"],
  ["2020, Family of the Year : The Ross Family (Troop 654, Charlotte)"],
  ["<hr>"],
  ["2019, Chartered Org of the Year : St. Gerard Catholic Church"],
  ["2019, Community Partner of the Year : Ingham County Parks Department"],
  ["2019, Advisor of the Year : Kevin Brown (Crew 2)"],
  ["2019, Scoutmaster of the Year : Chuck Leibrand (Troop 141)"],
  ["2019, Troop of the Year : Troop 141 (Mason)"],
  ["2019, Cubmaster of the Year : Sean Weise (Pack 265)"],
  ["2019, Pack of the Year : Pack 263 (Williamston)"],
  ["2019, Jack of all Trades : Colleen Cunningham (Linked Troop 2)"],
  ["2019, Rookie of the Year : Marla Ekola (Troop 164G)"],
  ["2019, Family of the Year : The Ramirez Family (Troop 77): Carrie, Phil, Isaiah"],
  ["<hr>"],
  ["2018, Chartered Org of the Year : Grand Ledge Masonic Lodge"],
  ["2018, Community Partner of the Year : Grace United Methodist Church"],
  ["2018, Advisor of the Year : Jeanette Hensler (Crew 43)"],
  ["2018, Crew of the Year : Crew 43"],
  ["2018, Scoutmaster of the Year : Alan Wright (Troop 111)"],
  ["2018, Troop of the Year : Troop 77"],
  ["2018, Cubmaster of the Year : Bryan Gehrcke"],
  ["2018, Pack of the Year : Pack 240"],
  ["2018, Jack of all Trades : Julie Bureau (Pack 240)"],
  ["2018, Rookie of the Year : Larry Fewins-Bliss (Pack 267)"],
  ["2018, Family of the Year : The Jones Family: Matthew, Melinda, Marcus & Maverick"],
  ["<hr>"],
  ["2017, Chartered Org of the Year : First Congregational Church of Charlotte"],
  ["2017, Community Partner of the Year : Dicks Sporting Goods"],
  ["2017, Post Advisor of the Year : Darlene Smith"],
  ["2017, Post of the Year : Post 989"],
  ["2017, Scoutmaster of the Year : Christopher Klaver (Troop 33)"],
  ["2017, Troop of the Year : Troop 763 (Mason)"],
  ["2017, Cubmaster of the Year : Aaron Todd (Pack 45)"],
  ["2017, Pack of the Year : Pack 260 (Grand Ledge)"],
  ["2017, Jack of all Trades : Ashley Foster"],
  ["2017, Rookie of the Year : Phil Dowker"],
  ["<hr>"],
  ["2016, Family of the Year : The Johnson Family"],
  ["2016, Chartered Org of the Year : Communities in School of Michigan"],
  ["2016, Community Partner of the Year : Quality Dairy"],
  ["2016, Advisor of the Year : Leila Rotschy (Crew 517)"],
  ["2016, Crew of the Year : Crew 43 (Dimondale)"],
  ["2016, Post Advisor of the Year : Helen Haag (Post 1060)"],
  ["2016, Scoutmaster of the Year : Ray Rustem (Troop 763)"],
  ["2016, Troop of the Year : Troop 2 (East Lansing)"],
  ["2016, Cubmaster of the Year : Dan Ward (Pack 141)"],
  ["2016, Pack of the Year : Pack 265"],
  ["2016, Jack of all Trades : Chuck Leibrand (Troop 141)"],
  ["2016, Rookie of the Year : Cate Saxton (Pack 519)"],
  ["2016, Family of the Year : The Chance Family"],
]
